using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Theta.ShipeventLobbyUI
{
    [GenerateTypedNameReferences]
    public sealed partial class LootboxMenu : DefaultWindow
    {
        public LootboxMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            Tabs.SetTabTitle(0, Loc.GetString("shipevent-ui-lootbox-tab-shop"));
            Tabs.SetTabTitle(1, Loc.GetString("shipevent-ui-lootbox-tab-inventory"));
        }
    }
}
