using Content.Shared.Theta.ShipEvent.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Theta.ShipEvent.UI;

//todo: add ability to kick members from team, make team announcements & other necessary stuff
[GenerateTypedNameReferences]
public sealed partial class CaptainMenuWindow : DefaultWindow
{
    public ShipPickerWindow shipPicker = default!;

    public event Action<BaseButton.ButtonEventArgs>? ShipPickerButtonPressed;
    public event Action<BaseButton.ButtonEventArgs>? BlackListButtonPressed;
    public event Action<BaseButton.ButtonEventArgs>? KickButtonPressed;
    public event Action<BaseButton.ButtonEventArgs>? SetMaxMembersButtonPressed;
    public event Action<BaseButton.ButtonEventArgs>? SetPasswordButtonPressed;

    public string BlacklistText => BlackListEdit.Text;
    public string KickCKey => KickCKeyEdit.Text;
    public string Password => PasswordEdit.Text;
    public int MaxMembers => MaxMembersEdit.Value;

    public CaptainMenuWindow()
    {
        RobustXamlLoader.Load(this);

        shipPicker = new ShipPickerWindow();
        MaxMembersEdit.IsValid = value => value >= 0 && value <= 100;
        MaxMembersEdit.InitDefaultButtons();

        ShipPickerButton.OnPressed += _ =>
        {
            shipPicker.OpenCentered();
            ShipPickerButtonPressed?.Invoke(_);
        };
        BlackListButton.OnPressed += _ =>
        {
            BlackListButtonPressed?.Invoke(_);
        };
        KickButton.OnPressed += _ =>
        {
            KickButtonPressed?.Invoke(_);
        };
        SetMaxMembersButton.OnPressed += _ =>
        {
            SetMaxMembersButtonPressed?.Invoke(_);
        };
        SetPasswordButton.OnPressed += _ =>
        {
            SetPasswordButtonPressed?.Invoke(_);
        };
    }

    public void UpdateState(ShipEventCaptainMenuBoundUserInterfaceState state)
    {
        MemberList.Text = string.Join(';', state.Members);
        ShipName.Text = Loc.GetString(state.CurrentShipType?.Name ?? "N/A");
        PasswordEdit.Text = state.Password ?? "";
        MaxMembersEdit.Value = state.MaxMembers == int.MaxValue ? 0 : state.MaxMembers;
    }
}
