using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Theta.ShipEvent.UI;

[GenerateTypedNameReferences]
public sealed partial class EnterPasswordWindow : DefaultWindow
{
    public event Action? EnterPasswordPressed;

    public string ChosenTeamName = "";

    public string Password => PasswordEdit.Text;

    public EnterPasswordWindow()
    {
        RobustXamlLoader.Load(this);
        Enter.OnPressed += _ =>
        {
            EnterPasswordPressed?.Invoke();
            ClearData();
            Close();
        };
        Cancel.OnPressed += _ =>
        {
            ClearData();
            Close();
        };
    }

    public void SaveChosenTeamName(string teamName)
    {
        ChosenTeamName = teamName;
    }

    private void ClearData()
    {
        ChosenTeamName = "";
        PasswordEdit.Text = "";
    }
}
