using Content.Shared.Theta.ShipEvent;
using Content.Shared.Theta.ShipEvent.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Theta.ShipEvent.UI;

[GenerateTypedNameReferences]
public sealed partial class ShipPickerWindow : DefaultWindow
{
    public event Action<EventArgs>? InfoRequest;

    public ShipType? Selection;
    
    public ShipPickerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(ShipPickerBoundUserInterfaceState state)
    {
        foreach (var shipType in state.ShipTypes)
        {
            var shipTypeEntry = new BoxContainer();
            var shipTypeEntryInfoHolder = new BoxContainer();
            shipTypeEntry.Orientation = BoxContainer.LayoutOrientation.Vertical;
            shipTypeEntryInfoHolder.Orientation = BoxContainer.LayoutOrientation.Horizontal;
            
            var shipTypeLabel = new RichTextLabel();
            shipTypeLabel.SetMessage($"{shipType.Name}\n{GetShipClassName(shipType.Class)}\n{shipType.Description}");
            shipTypeLabel.MinWidth = Window!.Size.X / 2;
            shipTypeLabel.SetWidth = shipTypeLabel.MinWidth;

            var shipTypePreviewImage = new TextureRect();
            shipTypePreviewImage.TexturePath = shipType.PreviewImage;

            var selectionButton = new Button();
            selectionButton.Text = Loc.GetString("shipevent-shippicker-selectionbutton");
            selectionButton.OnPressed += _ => Selection = shipType;

            shipTypeEntry.AddChild(shipTypeEntryInfoHolder);
            shipTypeEntry.AddChild(selectionButton);
            
            ShipOptionsContainer.AddChild(shipTypeEntry);
        }
    }

    private string GetShipClassName(ShipClass shipClass)
    {
        string className = "";
        switch (shipClass)
        {
            case ShipClass.Light:
                className = "light";
                break;
            case ShipClass.Medium:
                className = "medium";
                break;
            case ShipClass.Heavy:
                className = "heavy";
                break;
            case ShipClass.Special:
                className = "special";
                break;
        }
        return Loc.GetString("shipevent-shippicker-"+className+"class");
    }
}
