using Content.Shared.Theta.ShipEvent.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Theta.ShipEvent.UI;

/// <summary>
/// Window for ship event team-view action
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class TeamCreationWindow : DefaultWindow
{
    public event Action<BaseButton.ButtonEventArgs>? CreationButtonPressed;
    public string TeamName => NameEdit.Text;

    public Color TeamColor => ColorEdit.Color;

    public string Blacklist => BlacklistEdit.Text;

    public TeamCreationWindow()
    {
        RobustXamlLoader.Load(this);
        ColorEdit.OnColorChanged += _ => OnColorChanged(); //will runtime if no callback for this event is set
        CreationButton.OnPressed += _ => CreationButtonPressed?.Invoke(_);
    }

    public void OnColorChanged() { }

    public void UpdateState(ShipEventCreateTeamBoundUserInterfaceState state)
    {
        UserMessage.Text = state.UserMessage;
    }
}
