using Content.Client.Message;
using Content.Shared.Theta.ShipEvent.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Theta.ShipEvent.UI;

/// <summary>
/// Window for ship event team-view action
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class TeamViewWindow : DefaultWindow
{
    public TeamViewWindow()
    {
        RobustXamlLoader.Load(this);
        ActiveTeams.SetMessage(Loc.GetString("shipevent-teamview-heading"));
    }

    public void UpdateText(TeamViewBoundUserInterfaceState state)
    {
        GridContent.RemoveAllChildren();
        AddHeaders();

        foreach (var teamState in state.Teams)
        {
            var richText = new RichTextLabel();
            richText.MaxWidth = MinWidth / 4;

            richText.SetMarkup($"[color={teamState.Color.ToHex()}]{teamState.Name ?? "N/A"}[/color]");
            GridContent.AddChild(richText);

            richText = new RichTextLabel();
            richText.MaxWidth = MinWidth / 4;
            richText.SetMessage(!String.IsNullOrEmpty(teamState.ShipName) ? teamState.ShipName : "N/A");
            GridContent.AddChild(richText);

            richText = new RichTextLabel();
            richText.MaxWidth = MinWidth / 4;
            richText.SetMessage(teamState.AliveCrewCount ?? "N/A");
            GridContent.AddChild(richText);

            richText = new RichTextLabel();
            richText.MaxWidth = MinWidth / 4;
            richText.SetMessage(teamState.Points.ToString());
            GridContent.AddChild(richText);
        }
    }

    private void AddHeaders()
    {
        var richText = new RichTextLabel();
        richText.SetMessage(Loc.GetString("shipevent-teamview-heading-name"));
        GridContent.AddChild(richText);

        richText = new RichTextLabel();
        richText.SetMessage(Loc.GetString("shipevent-teamview-heading-shipname"));
        GridContent.AddChild(richText);

        richText = new RichTextLabel();
        richText.SetMessage(Loc.GetString("shipevent-teamview-heading-crew"));
        GridContent.AddChild(richText);

        richText = new RichTextLabel();
        richText.SetMessage(Loc.GetString("shipevent-teamview-heading-points"));
        GridContent.AddChild(richText);
    }
}
