using Content.Shared.Theta.ShipEvent;
using Content.Shared.Theta.ShipEvent.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Theta.ShipEvent.UI;

[GenerateTypedNameReferences]
public sealed partial class TeamCreationWindow : DefaultWindow
{
    public ShipPickerWindow ShipPicker;
    public event Action<BaseButton.ButtonEventArgs>? CreationButtonPressed;

    public event Action<BaseButton.ButtonEventArgs>? ShipPickerButtonPressed;

    public string TeamName => NameEdit.Text;

    public string Password => PasswordEdit.Text;

    public int MaxMembers => MaxMembersEdit.Value;

    public ShipTypePrototype? ShipType => ShipPicker.Selection;

    public TeamCreationWindow()
    {
        RobustXamlLoader.Load(this);
        ShipPicker = new ShipPickerWindow();
        CreationButton.OnPressed += _ => CreationButtonPressed?.Invoke(_);
        ShipPickerButton.OnPressed += _ =>
        {
            ShipPicker.OpenCentered();
            ShipPickerButtonPressed?.Invoke(_);
        };
        ShipPicker.OnSelectionMade += SetChosenShipLabel;
        SetChosenShipLabel();

        MaxMembersEdit.IsValid = value => value >= 0 && value <= 100;
        MaxMembersEdit.InitDefaultButtons();
    }

    private void SetChosenShipLabel(ShipTypePrototype? _ = null)
    {
        var desc = Loc.GetString("shipevent-teamcreation-ship");
        var ship = Loc.GetString(ShipPicker.Selection?.Name ?? "N/A");
        ShipLabel.Text = $"{desc} {ship}";
    }

    public void UpdateState(ShipEventCreateTeamBoundUserInterfaceState state)
    {
        UserMessage.Text = state.UserMessage;
    }

    public void Dispose()
    {
        base.Dispose();
        ShipPicker.Dispose();
    }
}
