using Content.Shared.Theta.ShipEvent.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Theta.ShipEvent.UI;

/// <summary>
/// Window for ship event team-view action
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class TeamCreationWindow : DefaultWindow
{
    public event Action<BaseButton.ButtonEventArgs>? CreationButtonPressed;
    public string _Name => NameEdit.Text;

    public string _Color => ColorEdit.Text;
    
    public string _Blacklist => BlacklistEdit.Text;

    public TeamCreationWindow()
    {
        RobustXamlLoader.Load(this);

        CreationButton.OnPressed += _ => CreationButtonPressed?.Invoke(_);
    }

    public void UpdateState(TeamCreationBoundUserInterfaceState state) { UserMessage.Text = state.UserMessage; }
}
