using Content.Shared.Theta.ShipEvent.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Theta.ShipEvent.UI;

[GenerateTypedNameReferences]
public sealed partial class TurretLoaderWindow : DefaultWindow
{
    public event Action<BaseButton.ButtonEventArgs>? EjectButtonPressed;
    public event Action<BaseButton.ButtonEventArgs>? RefreshButtonPressed;
    
    public TurretLoaderWindow()
    {
        RobustXamlLoader.Load(this);
        EjectContainerButton.OnPressed += _ => EjectButtonPressed?.Invoke(_);
        RefreshButton.OnPressed += _ => RefreshButtonPressed?.Invoke(_);
    }

    public void UpdateState(TurretLoaderBoundUserInterfaceState state)
    {
        StatusText.Text = state.Status;
        AmmoCount.Text = $"{state.AmmoCurrent}";
        TurretUid.Text = state.TurretUid.ToString();
    }
}
