using Content.Client.Message;
using Content.Shared.Theta.ShipEvent.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Theta.ShipEvent.UI;

[GenerateTypedNameReferences]
public sealed partial class TurretLoaderWindow : DefaultWindow
{
    public TurretLoaderWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(TurretLoaderBoundUserInterfaceState state)
    {
    }
}
