using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Theta.ShipeventLobbyUI.Tabs
{
    [GenerateTypedNameReferences]
    public sealed partial class LootboxShopTab : Control
    {
        public LootboxShopTab()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);
        }
    }
}
