using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client.UserInterface.Systems.Radar.Widgets;

[GenerateTypedNameReferences]
public sealed partial class RadarGui : UIWidget
{
    private const string OpenTexturePath = "/Textures/Interface/VerbIcons/pickup.svg.192dpi.png";
    private const string CloseTexturePath = "/Textures/Interface/VerbIcons/drop.svg.192dpi.png";

    public RadarGui()
    {
        RobustXamlLoader.Load(this);
        SetSize = new(400, 400);

        ToggleButton.TexturePath = CloseTexturePath;
        ToggleButton.OnPressed += ToggleRadar;
        LayoutContainer.SetAnchorAndMarginPreset(this, LayoutContainer.LayoutPreset.BottomRight, margin: 10);
    }

    public void SetMatrix(EntityCoordinates? coordinates, Angle? angle)
    {
        Radar.SetMatrix(coordinates, angle);
    }

    private void ToggleRadar(BaseButton.ButtonEventArgs obj)
    {
        Radar.Visible = !Radar.Visible;
        ToggleButton.TexturePath = Radar.Visible ? CloseTexturePath : OpenTexturePath;
    }
}
